export const POSTS_FETCH_INIT = 'POSTS_FETCH_INIT';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_FAIL = 'POSTS_FETCH_FAIL';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_DELETE = 'POST_DELETE';