export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const CART_ADD = 'CART_ADD';
export const CART_FETCH_ITEMS = 'CART_FETCH_ITEMS';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_CANCEL = 'PURCHASE_CANCEL';
export const PURCHASE_FINISHED = 'PURCHASE_FINISHED';