export const TODO_ADD = 'TODO_ADD';
export const TODO_HAS_BEEN_ADDED = 'TODO_HAS_BEEN_ADDED';
export const TODOS_SET = 'TODOS_SET';
export const TODOS_HAVE_BEEN_SET = 'TODOS_HAVE_BEEN_SET';
export const TODO_REMOVE = 'TODO_REMOVE';
export const TODO_HAS_BEEN_REMOVED = 'TODO_HAS_BEEN_REMOVED';
export const TODO_COMPLETE = 'TODO_COMPLETE';
export const TODO_HAS_BEEN_COMPLETED = 'TODO_HAS_BEEN_COMPLETED';